server:
  port: 8085
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
    username: sbb
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sbb.domain/**/dto/request, com.sbb.domain/**/dto/request
  configuration:
    map-underscore-to-camel-case: true